PREFIX research: <http://example.org/research#>
PREFIX rdfs : < http :// www . w3 . org /2000/01/ rdf-schema# >
PREFIX xsd : < http :// www . w3 . org /2001/ XMLSchema# >
PREFIX rdf : < http :// www . w3 . org /1999/02/22-rdf-syntax-ns# >
SELECT ?reviewerName (GROUP_CONCAT(DISTINCT ?expertise; SEPARATOR=", ") AS ?expertiseAreas)
WHERE {
?reviewer research:reviewed ?review ;
research:name ?reviewerName .
?review research:reviews ?paper .
?paper research:related_to/research:keyword ?expertise .
}
GROUP BY ?reviewer ?reviewerName